name: Lint Check
on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run lintKotlinFormat
        run: ./gradlew formatKotlin
      - uses: reviewdog/action-suggester@v1
        with:
          reporter: "github-pr-review"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}